apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-claim1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scw-bssd
  csi:
    driver: csi.scaleway.com
    volumeHandle: fr-par-1/ef9607b4-4073-4e8d-8a9d-e3449630d4df
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.csi.scaleway.com/zone
          operator: In
          values:
          - fr-par-1
