version: '3'
services:
  # Main Rails app
  app:
    image: rg.fr-par.scw.cloud/namespace-clever-hopper/mt4-app-g5:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # links:
    #   - db:mysql
    #   - redis:redis
    # depends_on:
    #   db:
    #     condition: service_healthy
    #command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
  worker:
    image: rg.fr-par.scw.cloud/namespace-clever-hopper/mt4-app-g5:latest
    env_file:
      - .env
    volumes:
      - .:/app
    # links:
    #   - db:mysql
    #   - redis:redis
    # depends_on:
    #   db:
    #     condition: service_healthy
    #command: bundle exec rake environment resque:work QUEUE=*
  # SQL Database
  # db:
  #   env_file:
  #     - .env
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     # - MYSQL_ROOT_PASSWORD=root
  #     # - MYSQL_PASSWORD=root
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  #     - MYSQL_DATABASE=${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     timeout: 20s
  #     retries: 10
  # Redis
  # redis:
  #   env_file:
  #     - .env
  #   image: redis:3.2.11
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"