version: '3'
services:
  # Main Rails app
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    links:
      - db:mysql
      - redis:redis
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
  # SQL Database
  db:
    image: mysql:5.7
    restart: always
    environment:
      # - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  # Redis
  redis:
    image: redis:3.2.11
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"